import type { Metadata } from "next";
import "./globals.css";
import {ThemeProvider} from "next-themes";

export const metadata: Metadata = {
  title: "Create Next Appdd",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: any) {
    return (
        <>
            <html lang="en" suppressHydrationWarning>
            <head ><title>{metadata.title}</title></head>
            <body>
            <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
            >
                {children}
            </ThemeProvider>
            </body>
            </html>
        </>
    )
}